# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-linux :
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
         sudo apt update
         sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libglew-dev
         
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        
    - name: run-vcpkg  
      uses: lukka/run-vcpkg@v11.5
      with:
        vcpkgJsonIgnores: '["**/vcpkg/**", "**/vendor/**"]'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      # not used as of right now, but will be used in the future
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries-linux
        path: ${{github.workspace}}/bin/

  build-windows:
      runs-on: windows-latest

      steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: run-vcpkg  
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgJsonIgnores: '["**/vcpkg/**", "**/vendor/**"]'
  
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
  
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-windows
          path: ${{github.workspace}}/bin/
  
